### ISSUE TITLE
Null is not an object

### ISSUE THREAD

**Issue by goodxodyd11** [Novadart/react-native-nfc#22]
I have an error about Null is not an obejct.
the Error is shown like
TypeError: TypeError: null is not an object (evaluating '_reactNative.NativeModules.ReactNativeNFC.getStartUpNfcData')
- node_modules\react-native-nfc\index.js:22:37 in _registerToEvents
- node_modules\react-native-nfc\index.js:40:21 in addListener
* src\screens\DepartureScreen.js:15:24 in bindNfcListener
* src\screens\DepartureScreen.js:12:8 in componentDidMount
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:15036:10 in commitLifeCycles
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:16636:8 in commitAllLifeCycles
- ... 18 more stack frames from framework internals

I did write manifest.xml and nfc_tect_filter.xml exactly same with documents provided.
and my package.json is like
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "axios": "^0.19.0",
    "expo": "^35.0.0",
    "jquery": "^3.4.1",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-animated-loader": "^0.0.8",
    "react-native-datepicker": "^1.7.2",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-indicators": "^0.13.0",
    "react-native-maps": "^0.25.0",
    "react-native-nfc": "^0.3.0",
    "react-native-nfc-manager": "^1.2.5",
    "react-native-reanimated": "~1.2.0",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.6",
    "react-navigation-stack": "^1.8.0"
  },
  "devDependencies": {
    "babel-preset-expo": "^7.0.0"
  },
  "private": true
}

and I coded DepartureScreen.js like
![image](https://user-images.githubusercontent.com/45235962/65814041-cf351b00-e217-11e9-8a11-2b7c3e0e0938.png)

please help!

**Comment by weiannnnn** [comment]
Having the same issue!

**Comment by vamshi9666** [comment]
You're in a expo project. To get this module work, you needd to link native deps which is nof possible in expo. Consider ejecting to a bare react native app.

**Comment by goodxodyd11** [comment]
Thank you, but the project is over. Instead of using this API, we were able to complete it successfully by replacing it with QR code. Thank you for your reply.
