### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by LoganArnett** [Novadart/react-native-nfc#9]
Getting this error when trying to get `react-native-nfc` up and running in my application:

```red
undefined is not an object (evaluating '_reactNative.NativeModules.ReactNativeNFC.getStartUpNfcData')
// or
Cannot read property 'getStartUpNfcData' of undefined
```

It throws this error as soon as I navigate to the Scan components route.

### Package.json
![image](https://user-images.githubusercontent.com/8780547/28034316-d0624c5e-657e-11e7-9d82-d93c5d8e946c.png)

### My Scan component looks like this:
```js
import React, { Component } from 'react';
import { View, Text, StyleSheet, Alert } from 'react-native';
import NFC, { NfcDataType, NdefRecordType } from "react-native-nfc";
import { Link } from 'react-router-native';

export default class Scan extends Component {
  constructor(props) {
    super(props);
  }
  componentDidMount() {
    this.scanNFC();
  }

  scanNFC() {
    NFC.addListener(payload => Alert.alert(JSON.stringify(payload.data, null, 2)))
  }

  render() {
    return (
      <View style={styles.container}>
        <Link to="/">
          <Text style={styles.welcome} >
            Scanning
          </Text>
        </Link>
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.85)'
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
    color: '#ffffff'
  }
})
```

### AndroidManifest.xml
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.mynfc"
    android:versionCode="1"
    android:versionName="1.0">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.NFC" />

    <uses-sdk
        android:minSdkVersion="23"
        android:targetSdkVersion="25" />

    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        android:launchMode="singleTask">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>

        <intent-filter>
            <action android:name="android.nfc.action.NDEF_DISCOVERED"/>
            <category android:name="android.intent.category.DEFAULT"/>
        </intent-filter>

        <intent-filter>
            <action android:name="android.nfc.action.TECH_DISCOVERED"/>
        </intent-filter>

        <meta-data android:name="android.nfc.action.TECH_DISCOVERED" android:resource="@xml/nfc_tech_filter" />
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>

```

**Comment by LoganArnett** [comment]
I did just realize that if I dismiss this error I am able to scan the tag and detect it, however, I am not able to see and utilize the information within my app, it opens the device detection page with a `Tag Detected` message. 

### So my questions are:
  1. How can I get rid of the error message above ☝️ 
  2. How can I scan and use the tag info within the app

**Comment by smitch88** [comment]
It sounds like you are not appropriately able to capture the tag type within one of your defined filters of the manifest (i.e its opening the native tag detection within android and not within your app is a sign that the app isnt actually capturing it). 

Can you show the`nfc_tech_filter` file? Do you know what types of tags and the data types that are encoded on the tags?

**Comment by smitch88** [comment]
I was able to pull down @LoganArnett personal repo and discovered that the native-module linkage was not done so the library was not really being pulled in. He needed to manually add the import and module initialization to `MainApplication.java` to fix the problem.

**Comment by henrikra** [comment]
@LoganArnett Can you close this then?

**Comment by deybvagm** [comment]
I have the same issue. My AndroidManifest.xml and Component are almost the same like @LoganArnett. In my MainApplication.java I have the import 
`import com.novadart.reactnativenfc.ReactNativeNFCPackage;`
and the I load the package in the `getPackages` method like this:
`protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new ReactNativeNFCPackage(),
            new RCTCameraPackage(),
            new VectorIconsPackage(),
            new RNDeviceInfo()
      );
    }`
My `nfc_tech_filter` looks like this:
`<resources xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">
    <tech-list>
        <tech>android.nfc.tech.IsoDep</tech>
        <tech>android.nfc.tech.NfcA</tech>
        <tech>android.nfc.tech.NfcB</tech>
        <tech>android.nfc.tech.NfcF</tech>
        <tech>android.nfc.tech.NfcV</tech>
        <tech>android.nfc.tech.Ndef</tech>
        <tech>android.nfc.tech.NdefFormatable</tech>
        <tech>android.nfc.tech.MifareClassic</tech>
        <tech>android.nfc.tech.MifareUltralight</tech>
        <tech>android.nfc.tech.NfcBarcode</tech>
    </tech-list>
</resources>`
The problem I think, is when I define the listener `NFC.addListener`, so for example if I define the this listener on a button action it fails when I press the button
Any ideas on what could  I be missing? Thanks
